export const fetchAccountMock = {
  account: {
    user_info: {
      first_name: 'LTV',
      last_name: 'Employee',
      email: 'vguzman+ff2@beenverified.com',
      phone_number: '8454890869',
      optout_options: false,
      user_code: '105756948',
      optout_deleted: false,
      join_date: '2019-05-09T16:11:48.000-04:00',
      signup_type: 'web',
      design_name: 'freshness',
      design_version: 'v2',
      tos_version_bad: false,
      pp_version_bad: false,
      noncompliant: false,
      tos_pending: false,
      'shut_down?': false,
      hide_person_video: false,
      hide_property_video: false,
      friends_and_family: false,
      user_in_recycling: false,
      recycling_date: null,
      is_self_searcher: false,
      seats: [],
      seat_status: null,
      invite_count: 0,
      has_connected_vehicles: false,
    },
    subscription_info: {
      free_user: false,
      'mobile_free?': false,
      public_plan_type: 'Free Plan',
      subscription_plan_unique_name: 'free',
      subscription_plan_internal_name:
        'Subscription_$0_Months_0FreeTrial_NonRecurring_1Limits_Free',
      subscription_state: 'Free',
      in_billable_state: false,
      recurring: false,
      public_price_description: 'Free',
      normalize_date: '2019-05-09T16:11:48.000-04:00',
      monitor_limit: 10,
      remaining_monitors: 10,
      credits_remaining: 0,
      monthly_reports_remaining: -1,
      monthly_report_limit: -1,
      recycling_reports_remaining: 10,
      subscription_features: {
        monthly_report_limit: 0,
        consumer_report_block_plan_name: '',
        unlimited_reports: false,
        unlimited_monitors: false,
        report_tier: 'person_report',
        monitor_limit: 0,
        daily_report_soft_limit: 10000,
        monthly_bjl_limit: 0,
        comp_reports_enabled: null,
        alertme_enabled: null,
        unlimited_bankruptcies: null,
        unlimited_liens_and_judgments: null,
        lien_and_judgment_limit: null,
        six_month_transaction_multiplier: null,
        default_design: null,
        default_search_bar: null,
        modal_family: null,
        bankruptcy_limit: null,
        session_lock_enabled: null,
        pdf_access: null,
        pro_account: null,
        hourly_report_soft_limit: 5,
        active_reports_limit: null,
        api_access: null,
      },
      money_amount: '$0.00',
      'show_unlimited_reports?': true,
      renewal_period: 0,
      renewal_period_type: 'Days',
    },
    upgrade_info: {
      upgrade_credits: 0,
    },
    search_counts: {
      replenishment_date: '2019-05-09',
      allocated_bankruptcies: -1,
      allocated_liens_and_judgments: -1,
      remaining_bankruptcies: -1,
      remaining_liens_and_judgments: -1,
    },
    notification: null,
    legal_doc_info: {
      active_tos_version: 2,
      active_privacy_policy_version: 2,
    },
    billing_info: {},
    sandboxed: false,
    alert_me: {
      has_access: true,
      settings: {
        id: 77,
        digest_enabled: false,
        push_digest_enabled: false,
        instant_enabled: false,
        push_instant_enabled: false,
        next_digest_mailing_at: '2019-06-09',
        created_at: '2022-10-19T19:10:48.000-04:00',
        updated_at: '2022-10-19T19:10:48.000-04:00',
      },
    },
    retention_info: {
      ran_report_on_self: true,
      ran_report_on_multiple_days: true,
      ran_report_on_family_member: false,
      ran_reverse_phone_search: true,
      ran_email_search: true,
      ran_professional_contact_search: false,
      ran_people_search: true,
      ran_property_search: false,
      ran_estate_value_search: false,
      created_monitor: null,
      created_monitor_on_self: null,
      created_monitor_on_family_member: null,
      created_monitor_on_property: null,
      created_monitor_on_email: null,
      created_monitor_on_their_email: null,
      has_used_mobile_app: false,
      has_used_website: true,
      downsell_plan_offered: null,
      downsell_plan_accepted: null,
      claimed_person_report: false,
      ran_username_search: true,
      ran_neighborhood_watch_search: false,
      ran_vehicle_search: false,
      claimed_report: false,
    },
    report_tags: {
      self_person_report_id: null,
    },
    active_ab_tests: {
      tests: [
        {
          id: 182,
          user_id: 133,
          source: 'optimizely',
          experiment_key: 'FTA-132_free_premium_data_v3',
          variation_key: 'FTA-132_variation',
          created_at: '2022-10-19T19:10:52.000-04:00',
          updated_at: '2022-10-19T19:10:52.000-04:00',
          whitelist: null,
        },
      ],
    },
    user_settings: {
      hide_reactivation_banner: null,
      hide_recurring_cancelled_banner: null,
      hide_bad_billing_banner: null,
      hide_credit_card_banner: null,
      hide_trial_welcome_banner: null,
      skip_creation_modal: null,
      hide_person_video: null,
      hide_property_video: null,
      hide_dark_web_banner: null,
      hide_dark_web_notifications: null,
      hide_unclaimed_money_banner: null,
      hide_unclaimed_money_ctas: null,
      hide_download_app_cta: false,
      hide_unclaimed_money_welcome_modal: null,
      hide_social_cleanup_cta: null,
      show_info_collection_screen: null,
      hide_how_bv_works_modal: null,
      hide_payment_update_required_modal: null,
      hide_onboarding_checklist_modal: null,
      show_higher_confidence_data_only: null,
      show_sales_tax_notice_modal: null,
      hide_rate_app_banner: null,
      hide_multi_seats_invite_modal: true,
      hide_criminal_records: null,
      hide_privacy_cta: null,
      hide_ps_vs_biz_modal: null,
      hide_own_fcra: null,
      hide_own_tos: null,
      show_section_learn_more: null,
      hide_cancel_downsell_modal: null,
      check_marketplace_step: null,
      dqs_completed: null,
      hide_passes_invite_modal: null,
      hide_sitejabber_widget: null,
      check_invites_step: null,
      check_extension_step: null,
      check_reward_1_step: null,
      check_reward_2_step: null,
      check_reward_3_step: null,
      hide_getting_started: null,
      high_confidence_toggle: true,
      check_list_completed: null,
      check_list_skipped: null,
      identity_hub_completed: null,
      tips_completed: null,
      first_report_modal_seen: null,
      openbay_callout_modal_seen: null,
      credit_hub_enrollment_completed: null,
    },
    staff_info: {
      admin: false,
      blacklister: false,
      staff: true,
      beta_tester: false,
    },
  },
  meta: {
    status: 200,
    free_user: false,
    mobile_free: false,
    subscription_state: 'free',
  },
};
